name: Move linked issues to QA Review (Projects v2)

on:
  pull_request:
    types: [closed]

permissions:
  contents: read
  pull-requests: read
  issues: write

jobs:
  move-to-qa-review:
    # Only run when the PR is actually merged AND into master
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Move PR and related issues to QA Review
        uses: leonsteinhaeuser/project-beta-automations@v2.2.1
        with:
          gh_token: ${{ secrets.PROJECTS_AUTOMATION_PAT }}
          user: connor-callaghan
          project_id: 2                
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: "In review"
          move_related_issues: true
